name: 'Pull Request conventional commit title rules'
description: 'Github action to enforce Pull Request title conventional commit syntax'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: npm ci
      shell: bash
    - run: node ${{ github.action_path }}/index.js
      shell: bash
