name: 'Pull Request conventional commit title rules'
description: 'GitHub action to enforce Pull Request title conventional commit syntax'
runs:
  using: "composite"
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'

    - run: |
        cd ${{ github.action_path }}
        npm ci
        node index.mjs
      shell: bash
